PREFIX ogc: <http://www.ogc.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#> 
PREFIX ine: <http://lod.ine.es/def/vocabulary/>
PREFIX sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#>
PREFIX sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX ex: <http://example.com/>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX geolinkeddata: <http://geo.linkeddata.es/ontology/> 

SELECT ?y ?a WHERE {
    ?s a ogc:administrativeunit ;
       ogc:nameunit "Madrid" ;
       geo:hasGeometry ?gs .

    ?y a geolinkeddata:Surgencias ;
        geo:hasGeometry ?gy ;
        ogc:area ?a .
    FILTER (geof:sfWithin(?gy, ?gs))
}
ORDER BY ASC(?a)